#!/bin/bash

cd "$(dirname "$0")" #Make sure that we are in the right working dir for the logs

while true
do
	if [ -e main.log ]
	then
		cp main.log lastrun.log
	fi

    echo "Start Run - `date`" | tee -a ./status.log

	# Start fifo listener
	php -f SendAlerts.php 2>&1 | tee -a ./sendalerts.log &
	PID=$!

	# Start main thread
	php -f Main.php 2>&1 | tee -a ./main.log || kill -9 $PID

	echo "End Run - `date`" | tee -a ./status.log

	sleep 5
done
